name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  update:
    uses: mscharley/.github/.github/workflows/renovate-changesets.yml@main
    secrets:
      token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}
