name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: mscharley/.github/.github/workflows/stale.yml@6ed05c913b7ae5ceb40b59bf597f0e4fc76f9b56 # main
    permissions:
      issues: write
      pull-requests: write
      discussions: write
