name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: mscharley/.github/.github/workflows/stale.yml@3ea5efb827af3ad6391fa1a055197cea50931c25 # main
    permissions:
      issues: write
      pull-requests: write
      discussions: write
