name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: mscharley/.github/.github/workflows/stale.yml@ae426a730765ce329007ee079c62ae0ab43a93c2 # main
    permissions:
      issues: write
      pull-requests: write
      discussions: write
