name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: mscharley/.github/.github/workflows/stale.yml@main
    permissions:
      issues: write
      pull-requests: write
